openapi: 3.0.0
info:
  title: API
  version: 1.0.0
paths:
  /tasks:           #раздел, имеющий 2 эндпоинта
    get:
      summary: Get all tasks    #что делает
      tags:                 #метка
        - tasks
      responses:                #Что получаем
        '200':
          description: A list of tasks      #Описание
          content:                #Что лежит внутри
            application/json:
              schema:     #Структура данных
                type: array
                items:    #элемент массива
                  $ref: '#/components/schemas/Task' # Ссылка на схему Task
    post:
      summary: Create a new task
      tags:
        - tasks
      requestBody:          #Тело (что нужно отправить)
        description: The task to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreate' #структура данных
      responses:
        '201':
          description: The created task
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
  /tasks/{id}:
    patch:
      summary: Update a task
      tags:
        - tasks
      parameters:
        - name: id    #параметр пути
          in: path    #параметр пути в url
          required: true
          schema:
            type: string  # строка
      requestBody:
        description: Task data to update
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdate'
      responses:
        '200':
          description: Task updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Task not found
    delete:
      summary: Delete a task
      tags:
        - tasks
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string 
      responses:
        '204':
          description: Task deleted successfully
        '404':
          description: Task not found

components:   #Описание всех структурных данных
  schemas:
    Task:
      type: object
      properties:   #Свойства
        id:
          type: string  
        task:
          type: string
        is_done:
          type: string
    TaskCreate:
      type: object
      required: [task]   #[] обозначает массив 
      properties:
        task:
          type: string
        is_done:
          type: string
    TaskUpdate:
      type: object
      properties:
        task:
          type: string
        is_done:
          type: string